/**
 * DESIGN.md generator + linter tests.
 *
 * Verifies:
 *   - Generator produces a file with frontmatter + canonical sections in order
 *   - All ExtractVibe-specific extension sections (Voice, Logos, Sources) appear
 *   - Hex colors land in frontmatter intact
 *   - Component frontmatter resolves token refs
 *   - Linter catches: duplicate sections, out-of-order sections, invalid hex,
 *     broken token refs, missing name, low contrast
 *   - Linter passes on a generator output
 */

import { describe, it, expect } from "vitest";

import { generateDesignMd } from "../lib/extractor/generate-design-md";
import { lintDesignMd } from "../lib/design-md-lint";
import { looksLikeBrandColor, colorSaturation } from "../lib/extractor/parse-visual";
import { mockBrandKitFull } from "./fixtures/mock-brand-kit-full";
import { mockBrandKitMinimal } from "./fixtures/mock-brand-kit-minimal";

describe("generateDesignMd", () => {
  it("produces frontmatter + canonical sections from a full kit", async () => {
    const result = await generateDesignMd(mockBrandKitFull, { useLlm: false });
    expect(result.content).toMatch(/^<!-- Generated by ExtractVibe/);
    expect(result.content).toMatch(/^---/m);
    expect(result.content).toMatch(/version: alpha/);
    expect(result.content).toMatch(/^name: /m);
    expect(result.content).toMatch(/^colors:/m);
  });

  it("emits canonical section headings in order", async () => {
    const result = await generateDesignMd(mockBrandKitFull, { useLlm: false });
    const headings = (result.content.match(/^## .+$/gm) || []).map((h) => h.trim());

    const idxOf = (name: string) => headings.findIndex((h) => h === `## ${name}`);

    // Required ordering for canonical sections that should appear
    const overview = idxOf("Overview");
    const colors = idxOf("Colors");
    const typo = idxOf("Typography");
    const components = idxOf("Components");
    const dosDonts = idxOf("Do's and Don'ts");

    expect(overview).toBeGreaterThanOrEqual(0);
    expect(colors).toBeGreaterThan(overview);
    expect(typo).toBeGreaterThan(colors);
    if (components !== -1 && dosDonts !== -1) {
      expect(dosDonts).toBeGreaterThan(components);
    }
  });

  it("includes ExtractVibe extension sections (Voice, Logos, Sources)", async () => {
    const result = await generateDesignMd(mockBrandKitFull, { useLlm: false });
    expect(result.content).toMatch(/^## Voice$/m);
    expect(result.content).toMatch(/^## Logos$/m);
    expect(result.content).toMatch(/^## Sources$/m);
  });

  it("includes the primary hex in frontmatter", async () => {
    const result = await generateDesignMd(mockBrandKitFull, { useLlm: false });
    const primary = mockBrandKitFull.colors?.lightMode?.primary?.hex;
    if (primary) {
      expect(result.content.toLowerCase()).toContain(primary.toLowerCase());
    }
  });

  it("appends -dark variants when dark mode present", async () => {
    const result = await generateDesignMd(mockBrandKitFull, { useLlm: false });
    if (mockBrandKitFull.colors?.darkMode?.primary?.hex) {
      expect(result.content).toMatch(/primary-dark:/);
    }
  });

  it("handles a minimal kit without crashing", async () => {
    const result = await generateDesignMd(mockBrandKitMinimal, { useLlm: false });
    expect(result.content).toContain("# ");
    expect(result.content).toContain("---");
  });

  it("falls back gracefully when LLM is disabled", async () => {
    const result = await generateDesignMd(mockBrandKitFull, { useLlm: false });
    // Deterministic prose path is used; result should still have an Overview section
    expect(result.content).toMatch(/^## Overview$/m);
    expect(result.proseDegraded).toBe(false); // useLlm: false is not a degradation
  });

  it("output passes its own linter (no errors on full kit)", async () => {
    const result = await generateDesignMd(mockBrandKitFull, { useLlm: false });
    expect(result.lintResult.errors).toEqual([]);
  });
});

describe("looksLikeBrandColor (role-assignment heuristic)", () => {
  it("rejects pure white", () => {
    expect(looksLikeBrandColor({ r: 255, g: 255, b: 255 })).toBe(false);
  });
  it("rejects near-white (#fafafa)", () => {
    expect(looksLikeBrandColor({ r: 250, g: 250, b: 250 })).toBe(false);
  });
  it("accepts saturated brand purple (#533afd)", () => {
    expect(looksLikeBrandColor({ r: 0x53, g: 0x3a, b: 0xfd })).toBe(true);
  });
  it("accepts saturated lime (#81b81a)", () => {
    expect(looksLikeBrandColor({ r: 0x81, g: 0xb8, b: 0x1a })).toBe(true);
  });
  it("accepts deep black (#0d0d0d) — many brands use it", () => {
    expect(looksLikeBrandColor({ r: 13, g: 13, b: 13 })).toBe(true);
  });
  it("rejects very light gray (#f5f5f5)", () => {
    expect(looksLikeBrandColor({ r: 245, g: 245, b: 245 })).toBe(false);
  });
});

describe("colorSaturation", () => {
  it("returns 0 for grayscale", () => {
    expect(colorSaturation({ r: 128, g: 128, b: 128 })).toBe(0);
  });
  it("returns near 1 for fully saturated", () => {
    expect(colorSaturation({ r: 255, g: 0, b: 0 })).toBe(1);
  });
  it("returns intermediate for mid-saturation", () => {
    const s = colorSaturation({ r: 0x53, g: 0x3a, b: 0xfd });
    expect(s).toBeGreaterThan(0.7);
  });
});

describe("lintDesignMd", () => {
  const VALID = `---
name: "Test"
description: "Test brand"
colors:
  primary: "#5e6ad2"
  surface: "#ffffff"
  on-surface: "#101012"
typography:
  body-md:
    fontFamily: Inter
---
# Test
## Overview
Foo.
## Colors
| Role | Hex |
| primary | \`#5e6ad2\` |
## Typography
Body.
`;

  it("passes valid file", () => {
    const r = lintDesignMd(VALID);
    expect(r.errors).toEqual([]);
    expect(r.ok).toBe(true);
  });

  it("flags duplicate sections", () => {
    const dup = VALID + "\n## Colors\nDup.\n";
    const r = lintDesignMd(dup);
    expect(r.errors.some((e) => e.rule === "duplicate-section")).toBe(true);
  });

  it("flags out-of-order sections", () => {
    const bad = `---\nname: "X"\ncolors:\n  primary: "#fff"\n---\n# X\n## Typography\nFoo\n## Colors\nBar\n`;
    const r = lintDesignMd(bad);
    expect(r.errors.some((e) => e.rule === "section-order")).toBe(true);
  });

  it("flags invalid hex", () => {
    const bad = `---\nname: "X"\ncolors:\n  primary: "not-a-color"\n  surface: "#fff"\n---\n# X\n`;
    const r = lintDesignMd(bad);
    expect(r.errors.some((e) => e.rule === "invalid-color")).toBe(true);
  });

  it("flags broken token references", () => {
    const bad = `---\nname: "X"\ncolors:\n  primary: "#fff"\ncomponents:\n  btn:\n    color: "{colors.does-not-exist}"\n---\n# X\n`;
    const r = lintDesignMd(bad);
    expect(r.errors.some((e) => e.rule === "broken-token-ref")).toBe(true);
  });

  it("requires name in frontmatter", () => {
    const bad = `---\ndescription: "no name"\n---\n# X\n`;
    const r = lintDesignMd(bad);
    expect(r.errors.some((e) => e.rule === "name-required")).toBe(true);
  });

  it("warns on missing primary", () => {
    const bad = `---\nname: "X"\ncolors:\n  secondary: "#abc"\n---\n# X\n`;
    const r = lintDesignMd(bad);
    expect(r.warnings.some((w) => w.rule === "no-primary")).toBe(true);
  });

  it("warns on low contrast (primary on surface)", () => {
    // light gray on white — well below WCAG AA
    const bad = `---\nname: "X"\ncolors:\n  primary: "#dddddd"\n  surface: "#ffffff"\n---\n# X\n`;
    const r = lintDesignMd(bad);
    expect(r.warnings.some((w) => w.rule === "low-contrast")).toBe(true);
  });

  it("warns when frontmatter missing entirely", () => {
    const noFm = `# Hello\n## Overview\nFoo.\n`;
    const r = lintDesignMd(noFm);
    expect(r.warnings.some((w) => w.rule === "frontmatter-missing")).toBe(true);
  });

  it("preserves unknown sections without errors", () => {
    const withCustom = VALID + "\n## Voice\nA section.\n## Logos\nAnother.\n## Sources\nLinks.\n";
    const r = lintDesignMd(withCustom);
    expect(r.errors).toEqual([]);
  });
});
