import { Link } from "react-router";
import { useState } from "react";
import {
  Sparkles,
  ArrowRight,
  Check,
  ExternalLink,
  Copy,
  FileText,
  Github,
} from "lucide-react";
import { Button } from "~/components/ui/button";
import { Badge } from "~/components/ui/badge";
import { MarketingLayout } from "~/components/marketing-layout";

export function meta() {
  return [
    { title: "DESIGN.md Generator — Drop-In Design Specs for AI Coding Agents | ExtractVibe" },
    {
      name: "description",
      content:
        "Generate Google-spec DESIGN.md files for any website. Drop into your project root and Cursor, Claude Code, v0, Lovable, and Bolt instantly know how to build on-brand UI.",
    },
    {
      property: "og:title",
      content: "DESIGN.md Generator — On-Brand UI for Every AI Coding Agent",
    },
    {
      property: "og:description",
      content:
        "Generate Google-spec DESIGN.md files for any website. Drop into project root, AI agents read it automatically.",
    },
  ];
}

const SAMPLE_LINEAR_DESIGN_MD = `<!-- Generated by ExtractVibe -->
---
version: alpha
name: "Linear"
description: "The system for product development."
colors:
  primary: "#5e6ad2"
  surface: "#f5f5f6"
  on-surface: "#101012"
  border: "#1f1f25"
  primary-dark: "#7e85e3"
  surface-dark: "#0e0e10"
typography:
  display-lg:
    fontFamily: "Inter Variable"
    fontSize: "56px"
    fontWeight: "590"
    lineHeight: "1.1"
    letterSpacing: "-0.02em"
  body-md:
    fontFamily: "Inter Variable"
    fontSize: "16px"
    fontWeight: "400"
    lineHeight: "1.5"
rounded:
  sm: "4px"
  md: "8px"
  full: "9999px"
components:
  button-primary:
    backgroundColor: "{colors.primary}"
    textColor: "#ffffff"
    rounded: "{rounded.md}"
    padding: "8px 16px"
---

# Linear — Design System

## Overview

Linear projects a sophisticated, high-performance, and forward-thinking image,
emphasizing efficiency and cutting-edge technology. The aesthetic is clean,
modern, and understated, designed for serious product development teams.

**Key Characteristics:**
- Vibe — modern, efficient, AI-driven, performance, sleek
- Comparable to — Notion, Figma, Vercel
- Design era — contemporary

## Colors

The palette is restrained and high-contrast, signaling precision and focus. A
single accent (#5e6ad2) carries the entire interface; everything else is
grayscale.
…`;

export default function DesignMdPage() {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(SAMPLE_LINEAR_DESIGN_MD).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <MarketingLayout>
      {/* ─── Hero ───────────────────────────────────────────────────────── */}
      <section className="mx-auto max-w-4xl px-4 sm:px-6 pt-20 pb-16 md:pt-28 md:pb-20">
        <Badge variant="outline" className="mb-6 gap-1.5">
          <Sparkles className="h-3 w-3" />
          New — DESIGN.md generation
        </Badge>
        <h1 className="font-display text-4xl font-bold tracking-tight md:text-6xl">
          On-brand UI for every <br className="hidden md:block" />
          AI coding agent.
        </h1>
        <p className="mt-6 max-w-2xl text-lg leading-relaxed text-[hsl(var(--muted-foreground))] md:text-xl">
          Every ExtractVibe extraction now generates a{" "}
          <code className="rounded bg-[hsl(var(--muted))] px-1.5 py-0.5 font-mono text-base">DESIGN.md</code>{" "}
          file. Drop it into your project root and Cursor, Claude Code, v0, Lovable, and Bolt instantly know how to build UI that matches the brand.
        </p>
        <div className="mt-10 flex flex-wrap gap-3">
          <Button asChild size="lg" className="h-12 px-6 gap-2">
            <Link to="/dashboard/extract">
              Generate DESIGN.md
              <ArrowRight className="h-4 w-4" />
            </Link>
          </Button>
          <Button asChild size="lg" variant="outline" className="h-12 px-6 gap-2">
            <a
              href="https://github.com/google-labs-code/design.md"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Github className="h-4 w-4" />
              View spec
              <ExternalLink className="h-3.5 w-3.5" />
            </a>
          </Button>
        </div>
      </section>

      {/* ─── What is DESIGN.md ──────────────────────────────────────────── */}
      <section className="border-t border-[hsl(var(--border))] bg-[hsl(var(--muted))]/20">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 py-16 md:py-24">
          <div className="grid gap-10 md:grid-cols-2 md:gap-16">
            <div>
              <h2 className="font-display text-3xl font-bold tracking-tight md:text-4xl">
                What is DESIGN.md?
              </h2>
              <p className="mt-5 text-base leading-relaxed text-[hsl(var(--muted-foreground))]">
                Open-sourced by Google Labs, DESIGN.md is to design what AGENTS.md is to dev workflow — a single Markdown file at the project root that AI coding agents read to understand the brand.
              </p>
              <p className="mt-4 text-base leading-relaxed text-[hsl(var(--muted-foreground))]">
                Frontmatter holds machine-readable design tokens (colors, typography, spacing, components). Markdown sections give agents the context they need: do's and don'ts, voice, sample copy, comparable brands.
              </p>
              <p className="mt-4 text-base leading-relaxed text-[hsl(var(--muted-foreground))]">
                Tools that read it include Cursor, Claude Code, Copilot, Windsurf, Lovable, v0, Bolt, and Google Stitch. The official CLI exports straight to W3C Design Tokens or Tailwind theme config.
              </p>
            </div>
            <div className="space-y-4">
              <div className="rounded-lg border border-[hsl(var(--border))] p-5">
                <div className="text-xs uppercase tracking-wider text-[hsl(var(--muted-foreground))] font-medium">
                  Spec
                </div>
                <div className="mt-2 font-mono text-sm">
                  github.com/google-labs-code/design.md
                </div>
                <div className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">
                  Open-sourced April 2026 · 8.4k+ stars · version{" "}
                  <code>alpha</code>
                </div>
              </div>
              <div className="rounded-lg border border-[hsl(var(--border))] p-5">
                <div className="text-xs uppercase tracking-wider text-[hsl(var(--muted-foreground))] font-medium">
                  Community
                </div>
                <div className="mt-2 font-mono text-sm">
                  github.com/VoltAgent/awesome-design-md
                </div>
                <div className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">
                  65k+ stars · curated examples from Vercel, Linear, Stripe, Notion, Figma
                </div>
              </div>
              <div className="rounded-lg border border-[hsl(var(--border))] p-5">
                <div className="text-xs uppercase tracking-wider text-[hsl(var(--muted-foreground))] font-medium">
                  Schema source
                </div>
                <div className="mt-2 font-mono text-sm">W3C Design Tokens (DTCG)</div>
                <div className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">
                  Frontmatter exports cleanly to{" "}
                  <code>tokens.json</code> and Tailwind theme.
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ─── Live preview ───────────────────────────────────────────────── */}
      <section className="border-t border-[hsl(var(--border))]">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 py-16 md:py-24">
          <div className="flex items-end justify-between gap-4 mb-6 flex-wrap">
            <div>
              <h2 className="font-display text-3xl font-bold tracking-tight md:text-4xl">
                Live preview
              </h2>
              <p className="mt-2 text-base text-[hsl(var(--muted-foreground))]">
                A real DESIGN.md generated by ExtractVibe — ready to drop into a project.
              </p>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={handleCopy} className="gap-1.5">
                {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
                {copied ? "Copied" : "Copy"}
              </Button>
              <Button asChild variant="outline" size="sm" className="gap-1.5">
                <a
                  href="/api/brand/linear.app/design.md"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <ExternalLink className="h-3.5 w-3.5" />
                  Full file
                </a>
              </Button>
            </div>
          </div>

          <div className="rounded-xl border border-[hsl(var(--border))] overflow-hidden">
            <div className="border-b border-[hsl(var(--border))] bg-[hsl(var(--muted))]/30 px-4 py-2.5 flex items-center gap-2">
              <FileText className="h-3.5 w-3.5 text-[hsl(var(--muted-foreground))]" />
              <span className="font-mono text-xs">linear.app / DESIGN.md</span>
              <Badge variant="outline" className="ml-auto text-[10px] tracking-wider uppercase">
                Lint OK
              </Badge>
            </div>
            <pre className="overflow-auto p-5 text-xs leading-relaxed font-mono max-h-[600px]">
              <code>{SAMPLE_LINEAR_DESIGN_MD}</code>
            </pre>
          </div>
        </div>
      </section>

      {/* ─── Agents ─────────────────────────────────────────────────────── */}
      <section className="border-t border-[hsl(var(--border))] bg-[hsl(var(--muted))]/20">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 py-16 md:py-24">
          <h2 className="font-display text-3xl font-bold tracking-tight md:text-4xl">
            Picked up automatically.
          </h2>
          <p className="mt-3 max-w-2xl text-base text-[hsl(var(--muted-foreground))]">
            DESIGN.md is the standard. Drop it at your project root once and every AI tool you use reads it.
          </p>
          <div className="mt-10 grid grid-cols-2 gap-3 md:grid-cols-3">
            {[
              { name: "Claude Code", note: "Anthropic CLI" },
              { name: "Cursor", note: "AI IDE" },
              { name: "GitHub Copilot", note: "VS Code agent" },
              { name: "Windsurf", note: "Codeium IDE" },
              { name: "Google Stitch", note: "Native consumer" },
              { name: "Lovable", note: "App generator" },
              { name: "v0", note: "Vercel" },
              { name: "Bolt", note: "StackBlitz" },
              { name: "Magic Patterns", note: "UI generator" },
            ].map((tool) => (
              <div
                key={tool.name}
                className="rounded-lg border border-[hsl(var(--border))] p-4"
              >
                <div className="font-medium">{tool.name}</div>
                <div className="text-xs text-[hsl(var(--muted-foreground))] mt-0.5">
                  {tool.note}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── How to ─────────────────────────────────────────────────────── */}
      <section className="border-t border-[hsl(var(--border))]">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 py-16 md:py-24">
          <h2 className="font-display text-3xl font-bold tracking-tight md:text-4xl">
            Generate one in 30 seconds.
          </h2>
          <ol className="mt-10 space-y-8">
            {[
              {
                n: "01",
                title: "Extract",
                body: (
                  <>
                    Run an extraction on any URL — through the dashboard, API, or LLM agent bootstrap.
                    <pre className="mt-3 rounded-lg bg-[hsl(var(--muted))] p-4 text-xs font-mono overflow-x-auto">
{`curl -X POST https://extractvibe.com/api/extract \\
  -H "x-api-key: ev_..." \\
  -H "Content-Type: application/json" \\
  -d '{"url": "https://stripe.com"}'`}
                    </pre>
                  </>
                ),
              },
              {
                n: "02",
                title: "Get the DESIGN.md",
                body: (
                  <>
                    The file is generated automatically alongside the JSON kit and cached at the public URL.
                    <pre className="mt-3 rounded-lg bg-[hsl(var(--muted))] p-4 text-xs font-mono overflow-x-auto">
{`curl https://extractvibe.com/api/brand/stripe.com/design.md > DESIGN.md`}
                    </pre>
                  </>
                ),
              },
              {
                n: "03",
                title: "Drop it in",
                body: (
                  <>
                    Save as <code className="rounded bg-[hsl(var(--muted))] px-1 py-0.5 font-mono">DESIGN.md</code> at your project root, sibling to <code className="rounded bg-[hsl(var(--muted))] px-1 py-0.5 font-mono">README.md</code>. Every supported agent picks it up automatically.
                  </>
                ),
              },
              {
                n: "04",
                title: "Validate (optional)",
                body: (
                  <>
                    Use the official Google CLI to lint and export tokens.
                    <pre className="mt-3 rounded-lg bg-[hsl(var(--muted))] p-4 text-xs font-mono overflow-x-auto">
{`npx @google/design.md lint DESIGN.md
npx @google/design.md export --format dtcg DESIGN.md > tokens.json
npx @google/design.md export --format tailwind DESIGN.md`}
                    </pre>
                  </>
                ),
              },
            ].map((step) => (
              <li key={step.n} className="grid gap-4 md:grid-cols-[80px_1fr]">
                <div className="font-display text-3xl font-bold text-[hsl(var(--muted-foreground))]/40 tabular-nums">
                  {step.n}
                </div>
                <div>
                  <h3 className="font-display text-lg font-semibold tracking-tight">
                    {step.title}
                  </h3>
                  <div className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">
                    {step.body}
                  </div>
                </div>
              </li>
            ))}
          </ol>
        </div>
      </section>

      {/* ─── What's in it ──────────────────────────────────────────────── */}
      <section className="border-t border-[hsl(var(--border))] bg-[hsl(var(--muted))]/20">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 py-16 md:py-24">
          <h2 className="font-display text-3xl font-bold tracking-tight md:text-4xl">
            What ExtractVibe puts in your DESIGN.md
          </h2>
          <div className="mt-8 grid gap-3 md:grid-cols-2">
            {[
              ["Frontmatter tokens", "Hex colors, type scale, rounded, spacing, components — exportable to W3C Design Tokens and Tailwind theme."],
              ["Overview", "LLM-generated atmosphere prose: archetype, comparable brands, emotional register."],
              ["Colors", "Light + dark mode tables with semantic roles. Dark variants suffixed with -dark."],
              ["Typography", "Family list (with weights + source) and full type scale (size / weight / line-height / letter-spacing)."],
              ["Layout & Shapes", "Base unit, container max-width, grid, border-radius scale."],
              ["Elevation & Depth", "All detected shadow stacks and gradients."],
              ["Components", "Button styles per variant — background, text, radius, padding, font."],
              ["Do's and Don'ts", "Inferred + (when discovered) extracted from the brand's own guidelines page."],
              ["Voice", "Tone spectrum (1–10 axes), copywriting style, sample copy from the actual site."],
              ["Logos", "Every detected logo variant with format, URL, and confidence."],
              ["Sources", "Permalink to brand kit, official guidelines URL, screenshot, raw JSON."],
              ["Lint-clean", "Validated against the Google spec inline. Errors caught before the file ships."],
            ].map(([title, body]) => (
              <div
                key={title}
                className="rounded-lg border border-[hsl(var(--border))] p-5"
              >
                <div className="flex items-start gap-3">
                  <Check className="mt-0.5 h-4 w-4 shrink-0 text-[hsl(var(--foreground))]" />
                  <div>
                    <div className="font-medium">{title}</div>
                    <div className="mt-1 text-sm text-[hsl(var(--muted-foreground))]">
                      {body}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── CTA ────────────────────────────────────────────────────────── */}
      <section className="border-t border-[hsl(var(--border))]">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 py-20 md:py-28 text-center">
          <h2 className="font-display text-3xl font-bold tracking-tight md:text-5xl">
            Ship on-brand UI from day one.
          </h2>
          <p className="mx-auto mt-5 max-w-xl text-base text-[hsl(var(--muted-foreground))]">
            Every extraction generates a DESIGN.md. Free tier includes 50 extractions per month.
          </p>
          <div className="mt-10 flex flex-wrap items-center justify-center gap-3">
            <Button asChild size="lg" className="h-12 px-6 gap-2">
              <Link to="/sign-up">
                Get started free
                <ArrowRight className="h-4 w-4" />
              </Link>
            </Button>
            <Button asChild size="lg" variant="outline" className="h-12 px-6 gap-2">
              <Link to="/docs/design-md.md">
                Read the docs
                <ExternalLink className="h-3.5 w-3.5" />
              </Link>
            </Button>
          </div>
        </div>
      </section>
    </MarketingLayout>
  );
}
